# Generated by Django 4.1.6 on 2023-02-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TW', 'Two-Wheeler'), ('TW', 'Three-Wheeler'), ('FW', 'Four-Wheeler')], max_length=2),
        ),
    ]
